name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test --compact --coverage --min=75
